# Generated by Django 3.2.20 on 2024-01-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prod', models.CharField(max_length=100, null=True)),
                ('titre_prod', models.CharField(max_length=200, null=True)),
                ('description_prod', models.TextField()),
                ('prix_prod', models.IntegerField()),
            ],
        ),
    ]
