# Generated by Django 3.2.20 on 2024-01-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description_prod',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_prod',
            field=models.IntegerField(null=True),
        ),
    ]
