# Generated by Django 3.2.20 on 2024-01-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_auto_20240108_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
